version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=chart
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chart
    ports:
      - "3306:3306" # 外部から接続可能
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql # データ永続化
  data_collector:
    build: ./data_collector
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=chart

volumes:
  mysql-data:
